name: Run Tests

on:
  push:
    branches: [main, dev, qa]
  pull_request:
    branches: [main, dev, qa]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requierements.txt

    - name: Run pytest
      run: pytest
